### ISSUE TITLE
Sorting preferences not saved anymore since v0.12.30

### ISSUE THREAD

**Issue by mbc07** [lostindark/DriverStoreExplorer#309]
Driver Store Explorer allow sorting the driver list by different criteria by clicking once or twice in the desired column (INF, Driver Class, Provider, Driver Version, etc.).

In versions older than 0.12.30, the sorting preference would be saved and the next time you launched the app, the same sorting from the last time would be loaded. Starting with 0.12.30, however, the sorting always revert to "Driver Class" in ascending order, regardless of what sorting was selected the last time the app was used.

Would it be possible to bring this feature back to the current versions?

**Comment by epman100** [comment]
the sorting problem is fixed in the [recent 0.12.55 release](https://github.com/lostindark/DriverStoreExplorer/releases/tag/v0.12.55)
please close this issue

**Comment by mbc07** [comment]
No, it's not fixed. I tested 0.12.55 before opening this issue. Steps to reproduce:

1) Launch Driver Store Explorer, wait until it finishes loading. Drivers will be sorted by "Driver Class" in ascending order.
2) Click the title of any of the other columns (e.g. "Provider"). Drivers will be sorted by that now.
3) Close Driver Store Explorer and launch it again. Drivers will be sorted by "Driver Class" in ascending order, instead of what was last selected in the previous launch.

This problem started on 0.12.30 and still happens in the current 0.12.55. Last version without this issue was 0.12.17...

**Comment by lostindark** [comment]
Is your Driver Store Explorer folder read only?
The tool will try to read/write the config in the same folder. If it fails, it will put the config in user app data folder. Maybe something happens in between.

**Comment by mbc07** [comment]
The folder where it's stored has proper write permissions and the other settings (language, window position/size, whether to use DISM or the native driver store API) are saved and reloaded just fine, `Rapr.user.config` is sitting right next to the executable. 

The issue is specifically with sorting, which always revert to "Driver Class" in ascending order, everything else works...

**Comment by Gjanosh61** [comment]
In my case I did not encounter any problem as highlighted above. I did various tests changing now one now the other when reopening the program it always remembers the last sorting setting.

v. 0.12.55.0

**Comment by mbc07** [comment]
Not sure what happened, but I deleted `Rapr.user.config` and relaunched 0.12.55, a fresh config file was created and the sorting preference is properly saved now. Closing this now...
