### ISSUE TITLE
buttons are too small now 

### ISSUE THREAD

**Issue by Thdub** [lostindark/DriverStoreExplorer#46]
buttons are too small now for other languages, misses end of text...
![capture](https://user-images.githubusercontent.com/37347541/48881565-5f474e80-ee16-11e8-85eb-653b35d7b6ef.JPG)

**Comment by lostindark** [comment]
Fixed in eded26d6a6c152067632725b9462de67cdf97eac

**Comment by Thdub** [comment]
Still not totally...Now in french we can see "Selectionnez les pilotes" which means "Select drivers" , so it
still miss the word "obsolètes" (which means obsolete/out-of-date/old) as in my translation.
Thanks for all your efforts anyway, using RAPR since long time so I decided to contribute.
